// Assuming related types are defined elsewhere:
// import { Tenant } from './Tenant';
// import { GasStation } from './GasStation';
import {userType } from "./auth";

export type Tenant = {
    id: number; // Assuming 'id' is the primary key auto-generated by Django
    name: string;
    address?: string | null; // Optional field (null=True, blank=True)
    created_at: string; // Or Date if you're handling dates as Date objects
};

export type GasStation = {
    id: string;
    location: string;
    name: string;
    tenant: Tenant | null; // Or tenantId: number if you're using IDs
    created_at: string; // Or Date
};

export type Plan = 'Trial' | 'Premium';

export type Subscription = {
    id: number;
    tenant: Tenant; // Or tenantId: number
    plan: Plan;
    start_date: string; // Or Date
    expiry_date?: string | null; // Optional field
    trial_period: number; // Defaults to 0
    paid_period: number; // Defaults to 0
    is_active: boolean; // Defaults to true
};

export type PaymentMethod = 'MobileMoney' | 'Cash' | 'Bank';

export type staff_type = {
    station: string, // Or stationId: number
    name : string,
    designation : string,
    address : string,
    user : userType | null,
}

export type Payment = {
    id: number;
    station: GasStation; // Or stationId: number
    date_paid: string; // Or Date
    amount: number;
    transaction_id?: string | null; // Optional field
    method: PaymentMethod;
    // Computed property, not stored directly
    // tenant?: Tenant; // Accessible via station.tenant if needed
};

export type EmployeeType = {
    id: string;
    station: GasStation; // Or stationId: number
    name : string,
    designation : string,
    address : string,
    user : userType,
}